name: 'Build docker container'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
            echo "Checking docker installation"
            if command -v docker &> /dev/null; then
                echo "Docker installation found"
            else
                echo "Docker installation not found. Docker will be installed"
                curl -fsSL https://get.docker.com | sh
            fi
      - name: Login to DockerHub container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}    
      - name: Docker Hub Description
        uses: https://git.claeyscloud.com/david/gitea-actions/dockerhub-description@main
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  
          repository: davidquinonescl/hyperion-docker
